# Generated by Django 4.0.4 on 2022-05-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Categoria anun')),
                ('img', models.ImageField(upload_to='media', verbose_name='Categoria nkar')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Shoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Shose name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_shose', to='main.category')),
            ],
            options={
                'verbose_name': 'Shoose',
                'verbose_name_plural': 'Shooses',
            },
        ),
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Brend name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Brendi nkar')),
                ('shoose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoose_name', to='main.shoose')),
            ],
            options={
                'verbose_name': 'Brend',
                'verbose_name_plural': 'Brends',
            },
        ),
    ]
